### ISSUE TITLE
[Feature request] Easy installation

### ISSUE THREAD

**Issue by Kristinita** [packagecontrol/package_reviewer#3]
### 1. Request

It would be nice, if you add easy installation for `package_reviewer`. For example, it would be nice if [**package will be add to PyPI**](http://peterdowns.com/posts/first-time-with-pypi.html).

### 2. Justification

Fewer steps when installing spend a users time.

### 3. Desirable behavior

    pip install package_reviewer

pip install package_reviewer with all dependencies.

Thanks.

**Comment by FichteFoll** [comment]
Maybe.

**Comment by FichteFoll** [comment]
I'll add a `setup.py` so you can install this using pip's git source option. I feel like that should be good enough, at least until I decide where I will be going with this.

Docs: https://pip.pypa.io/en/stable/reference/pip_install/#git

I will also add a console entry point with setuptools, so you'll be able to run `package_reviewer ...` instead of `python -m package_reviewer`.

**Comment by FichteFoll** [comment]
The package is now available on pypi as [`st-package-reviewer`](https://pypi.org/project/st-package-reviewer/#description) (112bd16500a98bf54f3e4da57bb9867bbae9e519). I renamed the package (and repo) in the process (89a7969083c5311e9a569deddd696a91781b41bc), to make it more clear that this is not just some random package reviewer but for Sublime Text packages. 

Of course, it took way longer than expected, duh.

In the process I also added CI via travis and a coverage report on coveralls (4317ae357c2a5bda9c85c2dcf3c881f8cce3c54d).
